application : moms-present
runtime : python27
api_version : 1
version : 1
threadsafe : true

libraries :
   - name : webapp2
     version : latest

   - name : jinja2
     version : latest

handlers :
   - url: /template
     static_dir: template

   - url : /js
     static_dir : static/js
     
   - url : /image
     static_dir : static/image

   - url : /css
     static_dir : static/css

   - url : /.*
     script : main.app
     

